# Generated by Django 3.1.13 on 2021-11-16 10:33

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('discord_id', models.CharField(max_length=30)),
                ('email_id', models.EmailField(max_length=100)),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number')),
                ('team_name', models.CharField(max_length=30)),
                ('college_name', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('discord_id', models.CharField(max_length=30)),
                ('email_id', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number')),
                ('college_name', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.registrations')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('date', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField()),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.registrations')),
            ],
        ),
    ]
