# Generated by Django 3.1.13 on 2021-11-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='team_members',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
