# Generated by Django 3.1.13 on 2021-11-16 12:16

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_auto_20211116_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrations',
            name='discord_id',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='email_id',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='discord_id',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Phone Number'),
        ),
    ]
