# Generated by Django 3.1.13 on 2021-11-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_auto_20211116_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='has_paid',
            field=models.BooleanField(default=False),
        ),
    ]
