# Generated by Django 3.1.13 on 2021-11-16 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_payment_has_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='registrations.registrations'),
        ),
    ]
