# Generated by Django 3.1.13 on 2021-11-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0007_auto_20211116_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='signature',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
