# Generated by Django 3.1.13 on 2021-11-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0008_auto_20211116_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='address',
            field=models.TextField(default='AS'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrations',
            name='district',
            field=models.CharField(default='as', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrations',
            name='pincode',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrations',
            name='state',
            field=models.CharField(default='As', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammember',
            name='address',
            field=models.TextField(default='Sfd'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammember',
            name='district',
            field=models.CharField(default='sf', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammember',
            name='pincode',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammember',
            name='state',
            field=models.CharField(default='A', max_length=50),
            preserve_default=False,
        ),
    ]
