# Generated by Django 3.1.13 on 2021-12-05 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0013_auto_20211205_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='winner',
            options={'ordering': ['position']},
        ),
    ]
