# Generated by Django 3.1.13 on 2021-11-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211118_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='platform',
            field=models.CharField(default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='blog',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
